# Generated by Django 3.0.2 on 2020-06-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
