# Generated by Django 3.0.2 on 2020-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0002_auto_20200628_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='unique_id',
            field=models.CharField(default=0, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
