# Generated by Django 3.0.2 on 2020-06-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0003_auto_20200628_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customproduct',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
