# Generated by Django 3.0.2 on 2020-06-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoting', '0004_auto_20200628_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproduct',
            name='image_url',
        ),
    ]
